### ISSUE TITLE
impossible to declare an int constant of Integer.MIN_VALUE

### ISSUE THREAD

**Issue by rmuir** [elastic/Painless#16]
same goes for Long.MIN_VALUE. When writing division overflow tests i had to use hacks like this:
`int x = -2147483647 - 1;` instead of `int x = -2147483648;`

**Comment by rmuir** [comment]
@jdconrad I think we can close this one now?

**Comment by jdconrad** [comment]
Yeah... sorry missed this issue when I did the PR.
